name: "frontend"
version: "3"
services:
  webapp:
    image: avmesquita/financas-app-localhost-frontend
    build: "."
    ports:
      - 80:80
    volumes:
      - ./wwwroot:/usr/share/nginx/html
    environment:
      - API-CONTROLE='http://localhost:3000'
      - API-CONSOLIDADO='http://localhost:3000'
      - GTAG='G-0BS7XFKQDG'
