version: '3'

services:

  mysql-db:
    image: mysql:8.0.37 
    #build: "."
    restart: unless-stopped    
    env_file: "./.env"      
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - 3306:3306
    stdin_open: true
    tty: true
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql      
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql-db
    networks:
      - default

volumes:
  mysql-volume:  
